// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ALdJneADZSLMmqDN3_Jc4Xc1Rqf9bpg',
    appId: '1:25344626951:web:0014e9a1c660fcfd4375a2',
    messagingSenderId: '25344626951',
    projectId: 'chat-app-a2e30',
    authDomain: 'chat-app-a2e30.firebaseapp.com',
    storageBucket: 'chat-app-a2e30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-DbODABEyMHP3BcnPEGFQeKreXxc41jw',
    appId: '1:25344626951:android:2885615449fb4b024375a2',
    messagingSenderId: '25344626951',
    projectId: 'chat-app-a2e30',
    storageBucket: 'chat-app-a2e30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2CUG6cGPC0bRvtPO5tfHdk2OYo6J6SaQ',
    appId: '1:25344626951:ios:770493e90fbf34084375a2',
    messagingSenderId: '25344626951',
    projectId: 'chat-app-a2e30',
    storageBucket: 'chat-app-a2e30.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2CUG6cGPC0bRvtPO5tfHdk2OYo6J6SaQ',
    appId: '1:25344626951:ios:770493e90fbf34084375a2',
    messagingSenderId: '25344626951',
    projectId: 'chat-app-a2e30',
    storageBucket: 'chat-app-a2e30.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8ALdJneADZSLMmqDN3_Jc4Xc1Rqf9bpg',
    appId: '1:25344626951:web:3ef688676591dc204375a2',
    messagingSenderId: '25344626951',
    projectId: 'chat-app-a2e30',
    authDomain: 'chat-app-a2e30.firebaseapp.com',
    storageBucket: 'chat-app-a2e30.appspot.com',
  );

}